import React,{useEffect,useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import{Activity,AlertCircle,Check,ChevronRight,Clock,Download,FileText,Menu,RefreshCw,Search,Server,Settings,Wifi,X,Eye,Database}from'lucide-react';
import'./styles.css';
const API=import.meta.env.VITE_API_URL||'http://localhost:5000';
const DEFAULT={device_information:true,performance:true,interfaces:true,subscribers:true,outages:true,charts:true,additional:true};
async function api(path,opt){const r=await fetch(API+path,opt);const j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.error||`Request failed (${r.status})`);return j}
function App(){const[page,setPage]=useState('dashboard'),[devices,setDevices]=useState([]),[selected,setSelected]=useState([]),[sections,setSections]=useState(DEFAULT),[period,setPeriod]=useState('24h'),[search,setSearch]=useState(''),[loading,setLoading]=useState(false),[error,setError]=useState(''),[report,setReport]=useState(null),[inspect,setInspect]=useState(null),[mobile,setMobile]=useState(false);
 const load=async()=>{try{setLoading(true);setDevices(await api('/api/devices'));setError('')}catch(e){setError(e.message)}finally{setLoading(false)}};useEffect(()=>{load()},[]);
 const filtered=useMemo(()=>devices.filter(d=>(`${d.name} ${d.model||''} ${d.type||''} ${d.role||''} ${d.ip||''}`).toLowerCase().includes(search.toLowerCase())),[devices,search]);
 const toggle=id=>setSelected(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id]);
 const generate=async()=>{if(!selected.length)return setError('Select at least one device.');try{setLoading(true);setError('');const j=await api('/api/reports/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({device_ids:selected,sections,period})});setReport(j);setPage('preview')}catch(e){setError(e.message)}finally{setLoading(false)}};
 const inspectOne=async id=>{try{setLoading(true);setError('');setInspect(await api(`/api/devices/${id}/inspect?period=${period}`));setPage('inspector')}catch(e){setError(e.message)}finally{setLoading(false)}};
 return <div className="app">{mobile&&<div className="backdrop" onClick={()=>setMobile(false)}/>}<aside className={mobile?'sidebar open':'sidebar'}><div className="brand"><div className="logo">U</div><div><b>UISP Reporter</b><span>Source-of-truth reporting</span></div>{mobile&&<button className="icon" onClick={()=>setMobile(false)}><X/></button>}</div><nav>{[['dashboard','Dashboard',Activity],['generate','Generate report',FileText],['devices','Devices',Server],['settings','Settings',Settings]].map(([id,label,I])=><button className={page===id?'nav active':'nav'} onClick={()=>{setPage(id);setMobile(false)}} key={id}><I size={18}/>{label}</button>)}</nav><div className="sidefoot"><span><i/> UISP backend</span><small>{API}</small></div></aside><main><header><button className="menu icon" onClick={()=>setMobile(true)}><Menu/></button><div><p className="eyebrow">UISP NETWORK REPORTING</p><h1>{page==='dashboard'?'Dashboard':page==='generate'?'Generate report':page==='devices'?'Devices':page==='inspector'?'UISP inspector':page==='preview'?'Report preview':'Settings'}</h1></div><button className="refresh" onClick={load}><RefreshCw size={16}/> Refresh</button></header>{error&&<div className="error"><AlertCircle size={17}/>{error}</div>}{page==='dashboard'&&<Dashboard devices={devices} selected={selected} setPage={setPage}/>} {page==='devices'&&<DeviceList devices={filtered} selected={selected} toggle={toggle} search={search} setSearch={setSearch} inspect={inspectOne}/>} {page==='generate'&&<Generate devices={filtered} allDevices={devices} selected={selected} toggle={toggle} search={search} setSearch={setSearch} sections={sections} setSections={setSections} period={period} setPeriod={setPeriod} generate={generate} loading={loading}/>} {page==='inspector'&&<Inspector data={inspect}/>} {page==='preview'&&report&&<Preview report={report}/>} {page==='settings'&&<SettingsPage/>}</main></div>}
function Dashboard({devices,selected,setPage}){const online=devices.filter(d=>String(d.status||'').toLowerCase().includes('online')).length;return <section><div className="hero"><div><p className="eyebrow">SOURCE OF TRUTH</p><h2>Report what UISP actually returns.</h2><p>The generator collects the selected device, detail, statistics, interfaces, outages and any successful type-specific responses. Nothing is invented to fit a switch-only template.</p><button className="primary" onClick={()=>setPage('generate')}>Create report <ChevronRight size={17}/></button></div><div className="hero-art"><Database size={75}/><span>LIVE DATA</span></div></div><div className="stats"><Stat icon={Server} label="UISP devices" value={devices.length}/><Stat icon={Wifi} label="Online" value={online}/><Stat icon={FileText} label="Selected" value={selected.length}/><Stat icon={Clock} label="Workflow" value="Ready"/></div><div className="cards"><Info title="Device-aware" text="AP, GPON, switch, router, wireless and other models are rendered from returned data."/><Info title="Live telemetry" text="Charts are created from time-series structures actually returned by UISP."/><Info title="No dropped fields" text="Successful payloads are preserved in the Additional UISP Information appendix."/><Info title="Multiple devices" text="Select several devices and receive one combined PDF."/></div></section>}
function Stat({icon:I,label,value}){return <div className="stat"><I size={19}/><span>{label}</span><strong>{value}</strong></div>}function Info({title,text}){return <div className="info"><div className="dot"><Check size={14}/></div><div><b>{title}</b><p>{text}</p></div></div>}
function DeviceList({devices,selected,toggle,search,setSearch,inspect}){return <section><div className="toolbar"><div className="search"><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search name, model, type, role or IP..."/></div><span>{selected.length} selected</span></div><div className="device-grid">{devices.map(d=><Device key={d.id} d={d} checked={selected.includes(d.id)} toggle={toggle} inspect={inspect}/>)}{!devices.length&&<Empty/>}</div></section>}
function Device({d,checked,toggle,inspect}){return <div className={checked?'device selected':'device'}><button className="selectbtn" onClick={()=>toggle(d.id)}><div className="check">{checked&&<Check size={14}/>}</div><div className="device-icon"><Server size={20}/></div><div className="device-main"><b>{d.name}</b><span>{d.model||'Unknown model'} {d.type?`• ${d.type}`:''}</span><small>{d.ip||'No IP returned'} {d.role?`• ${d.role}`:''}</small></div><div className="status"><i className={String(d.status||'').toLowerCase().includes('online')?'green':''}/>{d.status||'Unknown'}</div></button><button className="inspect-btn" onClick={()=>inspect(d.id)} title="Inspect live UISP payload"><Eye size={16}/></button></div>}
function Generate({devices,allDevices,selected,toggle,search,setSearch,sections,setSections,period,setPeriod,generate,loading}){const all=allDevices.length>0&&selected.length===allDevices.length;const toggleAll=()=>{if(all){selected.forEach(toggle)}else{allDevices.forEach(d=>{if(!selected.includes(d.id))toggle(d.id)})}};return <section><div className="step"><span className="done">1</span><b>Choose devices</b><div/><span>2</span><b>Configure</b><div/><span>3</span><b>Generate</b></div><div className="config"><div className="panel"><div className="panel-title"><div><p className="eyebrow">DEVICE SELECTION</p><h3>Select from live UISP inventory</h3></div><button className="text-btn" onClick={toggleAll}>{all?'Clear all':'Select all'}</button></div><div className="search"><Search size={16}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search..."/></div><div className="mini-list">{devices.map(d=><Device key={d.id} d={d} checked={selected.includes(d.id)} toggle={toggle} inspect={()=>{}}/> )}</div></div><div className="panel"><p className="eyebrow">REPORT CONTENT</p><h3>Sections</h3><p className="muted">Structured sections are convenience views. The raw UISP appendix remains enabled by default so returned fields are not lost.</p><div className="section-list">{[['device_information','Device information'],['performance','Performance / statistics'],['interfaces','Interfaces / ports'],['subscribers','Stations / subscribers'],['outages','Outage history'],['charts','Telemetry charts'],['additional','Complete UISP appendix']].map(([k,l])=><label key={k}><span><b>{l}</b><small>{k==='additional'?'Preserve successful endpoint payloads':'Render only when UISP provides the data'}</small></span><input type="checkbox" checked={!!sections[k]} onChange={e=>setSections({...sections,[k]:e.target.checked})}/><em/></label>)}</div><div className="period"><b>Telemetry window</b><div className="periods">{[['1h','1 hour'],['6h','6 hours'],['24h','24 hours'],['7d','7 days']].map(([v,l])=><button key={v} className={period===v?'chosen':''} onClick={()=>setPeriod(v)}>{l}</button>)}</div></div><button className="primary wide" disabled={loading||!selected.length} onClick={generate}>{loading?'Collecting UISP data...':<>Generate PDF <ChevronRight size={17}/></>}</button></div></div></section>}
function Inspector({data}){if(!data)return <section><div className="panel"><h3>No inspection loaded</h3></div></section>;return <section><div className="panel"><p className="eyebrow">LIVE COLLECTION</p><h3>UISP inspector</h3><p className="muted">This screen shows which requests succeeded and the exact payloads returned for the selected device.</p><div className="endpoint-grid">{data.endpoints?.map((e,i)=><div className={e.ok?'endpoint ok':'endpoint bad'} key={i}><b>{e.name}</b><code>{e.path}</code><span>{e.ok?'✓ returned data':e.error}</span></div>)}</div><div className="raw"><h4>Raw device response</h4><pre>{JSON.stringify(data.device,null,2)}</pre><h4>Raw detail response</h4><pre>{JSON.stringify(data.detail,null,2)}</pre></div></div></section>}
function Preview({report}){return <section><div className="preview-top"><div><p className="eyebrow">GENERATED REPORT</p><h2>{report.collected_devices} device report</h2><p className="muted">The PDF is built from live UISP responses. Failed selected devices are reported below if applicable.</p>{report.failed_devices?.length>0&&<div className="warn">{report.failed_devices.join(' | ')}</div>}</div><a className="primary" href={API+report.download_url} download><Download size={17}/> Download PDF</a></div><div className="pdf-frame"><iframe src={API+report.preview_url} title="UISP report preview"/></div></section>}
function SettingsPage(){return <section><div className="panel"><p className="eyebrow">SECURITY</p><h3>Backend-only credentials</h3><p className="muted">Keep UISP_URL and UISP_API_TOKEN in backend/.env. React never receives the token.</p><div className="setting-row"><span>Backend API</span><code>{API}</code></div><div className="setting-row"><span>UISP source</span><b>Live API</b></div><div className="setting-row"><span>Report format</span><b>PDF</b></div></div></section>}
function Empty(){return <div className="empty">No UISP devices matched your search.</div>}
createRoot(document.getElementById('root')).render(<App/>);
